runtime: python38 # Define the python version pre-installed on the machine
# service: longest-world # Give a name to your app (comment if first time pushing to GAE)
handlers: # Define how to handle incoming requests. Here, any request will be handled by main.py
- url: /.*
  script: main.py
